# Generated by Django 4.2.1 on 2023-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0006_officer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
