# Generated by Django 4.2.1 on 2023-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0007_delete_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=150)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('duty', models.CharField(choices=[('fireforce', 'fireforce'), ('forest_officer', 'forest_officer'), ('sea_officer', 'sea_officer'), ('doctor', 'doctor')], max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('landmart', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
