# Generated by Django 4.2.1 on 2023-07-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0008_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(choices=[('user', 'user'), ('officer', 'officer')], default='user', max_length=20),
        ),
    ]
